spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.31.121/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
#  当返回给前端的值为null时,不返回该字段
#    default-property-inclusion: non_null
  freemarker:
    template-loader-path: classpath:/templates/
    charset: utf-8
    cache: false
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
    suffix: .ftl
  redis:
    host: 192.168.31.121
    port: 6379

server:
  context-path: /sell
  port: 80

wechat:
  mpAppId: wxbb88a700afa6dc82
  mpAppSecret: f73eb8887db000027f36013a792a72f7
  mchId:
  mchkey:
  keyPath:
  notify:

